### ISSUE TITLE
Questions about adversarial suffix generation

### ISSUE THREAD

**Issue by Syyabb** [tml-epfl/llm-adaptive-attacks#8]
Hello author，
Thank you for your dedication and contribution. 
It seems that in your method, for each prompt, we need to search for a unique adversarial suffix, rather than searching for an universarial adversarial suffix for multiple prompts. Do I understand correctly, and if I understand correctly, whether you have tested the performance of jailbreak when generating a universarial suffix?

**Comment by max-andr** [comment]
Hi,
We haven't evaluated universal suffixes in this paper. All suffixes optimized by random search are model- and request-specific. The prompt template, however, is universal.
